//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentNote
    {
        public int NotesID { get; set; }
        public Nullable<int> Usrno { get; set; }
        public string NotesTitle { get; set; }
        public string Tag { get; set; }
        public string Priority { get; set; }
        public string Descriptions { get; set; }
        public Nullable<bool> IsImportant { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
