//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airline
    {
        public int AirlineID { get; set; }
        public string Name { get; set; }
        public string IATA_Code { get; set; }
        public string ICAO_Code { get; set; }
        public string Country { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
