//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryMaster
    {
        public int Id { get; set; }
        public string CountryName { get; set; }
        public string ISO2 { get; set; }
        public string ISO3 { get; set; }
        public string PhoneCode { get; set; }
        public string CurrencyName { get; set; }
        public string CurrencyCode { get; set; }
        public string CurrencySymbol { get; set; }
    }
}
