//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlightBookingHistory
    {
        public int BookHistoryID { get; set; }
        public int Usrno { get; set; }
        public string TripType { get; set; }
        public string Sector { get; set; }
        public string DepartureDates { get; set; }
        public string ArrivalDates { get; set; }
        public int Adults { get; set; }
        public int Childs { get; set; }
        public int Infants { get; set; }
        public string CabinClass { get; set; }
        public string FlightOrderID { get; set; }
        public string QueuingOfficeId { get; set; }
        public string PaymentMode { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal DiscountAmount { get; set; }
        public decimal PaybleAmount { get; set; }
        public string PaymentStatus { get; set; }
        public string PaymentOrderID { get; set; }
        public string BookingStatus { get; set; }
        public string BookingDescription { get; set; }
        public System.DateTime AddDate { get; set; }
    }
}
