//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportchatAttachFile
    {
        public int AttachFileID { get; set; }
        public Nullable<int> SupportChatID { get; set; }
        public string Path { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
