//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportChat
    {
        public int SupportChatID { get; set; }
        public Nullable<int> SenderUsrno { get; set; }
        public Nullable<int> ReceiverUsrno { get; set; }
        public string Message { get; set; }
        public string Attachfile { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsBlock { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
