//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount_MainDetails
    {
        public int ID { get; set; }
        public Nullable<int> UsrNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public string Factor { get; set; }
        public string Narration { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string Remark { get; set; }
        public string TransactionId { get; set; }
    }
}
