//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFlight_SearchLog
    {
        public int SearchLogID { get; set; }
        public Nullable<int> Usrno { get; set; }
        public string TripType { get; set; }
        public string Origin { get; set; }
        public string Destination { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> AdultCount { get; set; }
        public Nullable<int> ChildCount { get; set; }
        public Nullable<int> InfantCount { get; set; }
        public string TravelClass { get; set; }
        public Nullable<bool> IsBook { get; set; }
        public string IPAddress { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
