//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFlightConnectionVia
    {
        public int FlightConnectionViaID { get; set; }
        public int FlightInventoryID { get; set; }
        public string Operator { get; set; }
        public string Flight { get; set; }
        public string FlightNo { get; set; }
        public string OriginCode { get; set; }
        public Nullable<System.TimeSpan> DepatureTime { get; set; }
        public string DepatureTerminal { get; set; }
        public string DestinationCode { get; set; }
        public Nullable<System.TimeSpan> ArrivalTime { get; set; }
        public string ArrivalTerminal { get; set; }
        public Nullable<bool> IsNextDay { get; set; }
        public Nullable<bool> DepatureOnNextDay { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    
        public virtual tblFlightInventory tblFlightInventory { get; set; }
    }
}
