//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFlightFare
    {
        public int FlightFareID { get; set; }
        public int FlightInventoryID { get; set; }
        public string ClassType { get; set; }
        public string RBD { get; set; }
        public Nullable<int> Seats { get; set; }
        public Nullable<int> AdultFare { get; set; }
        public Nullable<decimal> AdultFareBreakup { get; set; }
        public Nullable<int> ChildFare { get; set; }
        public Nullable<decimal> ChildFareBreakup { get; set; }
        public Nullable<int> InfantFare { get; set; }
        public Nullable<decimal> InfantFareBreakup { get; set; }
        public Nullable<bool> IsBaggage { get; set; }
        public Nullable<int> AdultBaggage { get; set; }
        public Nullable<int> ChildBaggage { get; set; }
        public Nullable<int> InfantBaggage { get; set; }
        public string Unit { get; set; }
        public Nullable<bool> IsRefund { get; set; }
        public string PNR { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    
        public virtual tblFlightInventory tblFlightInventory { get; set; }
    }
}
