//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFlightInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblFlightInventory()
        {
            this.tblFlightConnectionVias = new HashSet<tblFlightConnectionVia>();
            this.tblFlightFares = new HashSet<tblFlightFare>();
        }
    
        public int FlightInventoryID { get; set; }
        public int Usrno { get; set; }
        public string AirlineCode { get; set; }
        public string FlightNumber { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime Todate { get; set; }
        public string OriginCode { get; set; }
        public System.TimeSpan DepartureTime { get; set; }
        public string DepartureTerminal { get; set; }
        public string DestinationCode { get; set; }
        public System.TimeSpan ArrivalTime { get; set; }
        public string ArrivalTerminal { get; set; }
        public string FareRules { get; set; }
        public Nullable<int> FareDisplayType { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> StopTicketingDays { get; set; }
        public Nullable<System.TimeSpan> StopTicketingTime { get; set; }
        public string AvailableDays { get; set; }
        public string ConnectionType { get; set; }
        public Nullable<int> Stops { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFlightConnectionVia> tblFlightConnectionVias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblFlightFare> tblFlightFares { get; set; }
    }
}
