//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHistory_FundRequest
    {
        public int ID { get; set; }
        public Nullable<int> Usrno { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string UTRNo { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string PaymentMode { get; set; }
        public string BankName { get; set; }
        public string TransactionProof { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
    }
}
