//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManage_CreditLimit
    {
        public int ID { get; set; }
        public Nullable<int> Usrno { get; set; }
        public Nullable<int> CreditTypeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> RequestedAmount { get; set; }
        public Nullable<decimal> UsedAmount { get; set; }
        public Nullable<decimal> AvailableAmount { get; set; }
        public Nullable<int> Days { get; set; }
        public string Remark { get; set; }
        public string AdminRemark { get; set; }
        public string AttachFile { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsRejected { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
        public Nullable<int> ActionByUsrno { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
