//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster_CreditType
    {
        public int CreditTypeId { get; set; }
        public string CreditType { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
