//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManage_AssignAPI
    {
        public int AssignId { get; set; }
        public int Usrno { get; set; }
        public int APIID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual tblManage_API tblManage_API { get; set; }
    }
}
