//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManage_AgentKYC
    {
        public int ID { get; set; }
        public int Usrno { get; set; }
        public Nullable<int> AgencyTypeID { get; set; }
        public string AgencyName { get; set; }
        public string PanNumber { get; set; }
        public string PancardImg { get; set; }
        public string GstNumber { get; set; }
        public Nullable<int> BusinessTypeId { get; set; }
        public string AgencyAddress { get; set; }
        public string Pincode { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> KycDocumentTypeId { get; set; }
        public string DocumentFile { get; set; }
        public Nullable<int> SupportingDocumentTypeId { get; set; }
        public string SupportingDocumentFile { get; set; }
        public bool IsApproved { get; set; }
        public bool IsRejected { get; set; }
        public string Remark { get; set; }
        public System.DateTime AddDate { get; set; }
        public Nullable<int> CreatedByUsrno { get; set; }
    }
}
