//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManage_UserInvited
    {
        public int ID { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> InvitedUsrno { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
