//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManage_API
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblManage_API()
        {
            this.tblManage_AssignAPI = new HashSet<tblManage_AssignAPI>();
        }
    
        public int APIID { get; set; }
        public string Supplier { get; set; }
        public string APIType { get; set; }
        public string LiveEndPointUrl { get; set; }
        public string LiveClientId { get; set; }
        public string LiveClientSecret { get; set; }
        public string TestEndPointUrl { get; set; }
        public string TestClientId { get; set; }
        public string TestClientSecret { get; set; }
        public Nullable<bool> IsLive { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblManage_AssignAPI> tblManage_AssignAPI { get; set; }
    }
}
