//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManage_CityAirport
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string ICAOCode { get; set; }
    }
}
