//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMaster_Menu
    {
        public int ID { get; set; }
        public string MenuName { get; set; }
        public string URL { get; set; }
        public string PageName { get; set; }
        public string Icon { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public Nullable<int> MenuLevel { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> SubParentID { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
