//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManage_CompanyAccount
    {
        public int ID { get; set; }
        public string AccountNo { get; set; }
        public string HolderName { get; set; }
        public string IFSCCode { get; set; }
        public string BankName { get; set; }
        public string AccountType { get; set; }
        public string Branch { get; set; }
        public string BranchLocation { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
