//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblManage_Markup
    {
        public int ID { get; set; }
        public Nullable<int> MarkupTypeID { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public Nullable<int> MethodID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> MarkupCategoryId { get; set; }
        public Nullable<int> Usrno { get; set; }
        public string AirlineCode { get; set; }
        public Nullable<int> CreatedByUsrno { get; set; }
        public Nullable<bool> IsUniversal { get; set; }
        public Nullable<bool> IsUniversalOverride { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
    }
}
