//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_silviEntities : DbContext
    {
        public db_silviEntities()
            : base("name=db_silviEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgentNote> AgentNotes { get; set; }
        public virtual DbSet<Airline> Airlines { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CountryMaster> CountryMasters { get; set; }
        public virtual DbSet<CreditWallet> CreditWallets { get; set; }
        public virtual DbSet<CreditWalletStatement> CreditWalletStatements { get; set; }
        public virtual DbSet<ErrorLog> ErrorLogs { get; set; }
        public virtual DbSet<FlightBookingHistory> FlightBookingHistories { get; set; }
        public virtual DbSet<SupportchatAttachFile> SupportchatAttachFiles { get; set; }
        public virtual DbSet<SupportChat> SupportChats { get; set; }
        public virtual DbSet<tblAccount_Main> tblAccount_Main { get; set; }
        public virtual DbSet<tblAccount_MainDetails> tblAccount_MainDetails { get; set; }
        public virtual DbSet<tblFlight_SearchLog> tblFlight_SearchLog { get; set; }
        public virtual DbSet<tblFlightConnectionVia> tblFlightConnectionVias { get; set; }
        public virtual DbSet<tblFlightFare> tblFlightFares { get; set; }
        public virtual DbSet<tblFlightInventory> tblFlightInventories { get; set; }
        public virtual DbSet<tblHistory_FundRequest> tblHistory_FundRequest { get; set; }
        public virtual DbSet<tblManage_AgentKYC> tblManage_AgentKYC { get; set; }
        public virtual DbSet<tblManage_API> tblManage_API { get; set; }
        public virtual DbSet<tblManage_AssignAPI> tblManage_AssignAPI { get; set; }
        public virtual DbSet<tblManage_CityAirport> tblManage_CityAirport { get; set; }
        public virtual DbSet<tblManage_CompanyAccount> tblManage_CompanyAccount { get; set; }
        public virtual DbSet<tblManage_Coupons> tblManage_Coupons { get; set; }
        public virtual DbSet<tblManage_CreditLimit> tblManage_CreditLimit { get; set; }
        public virtual DbSet<tblManage_Customer> tblManage_Customer { get; set; }
        public virtual DbSet<tblManage_Markup> tblManage_Markup { get; set; }
        public virtual DbSet<tblManage_MenuRights> tblManage_MenuRights { get; set; }
        public virtual DbSet<tblManage_UserInvited> tblManage_UserInvited { get; set; }
        public virtual DbSet<tblMaster_AgencyType> tblMaster_AgencyType { get; set; }
        public virtual DbSet<tblMaster_Bank> tblMaster_Bank { get; set; }
        public virtual DbSet<tblMaster_BusinessType> tblMaster_BusinessType { get; set; }
        public virtual DbSet<tblMaster_City> tblMaster_City { get; set; }
        public virtual DbSet<tblMaster_CreditType> tblMaster_CreditType { get; set; }
        public virtual DbSet<tblMaster_KYCDocumentType> tblMaster_KYCDocumentType { get; set; }
        public virtual DbSet<tblMaster_Menu> tblMaster_Menu { get; set; }
        public virtual DbSet<tblMaster_State> tblMaster_State { get; set; }
        public virtual DbSet<tblMaster_SupportingDocumentType> tblMaster_SupportingDocumentType { get; set; }
        public virtual DbSet<tblMaster_User> tblMaster_User { get; set; }
        public virtual DbSet<tblMaster_UserType> tblMaster_UserType { get; set; }
        public virtual DbSet<tblUser_LevelDownline> tblUser_LevelDownline { get; set; }
        public virtual DbSet<tblOTPVerification> tblOTPVerifications { get; set; }
        public virtual DbSet<View_Users> View_Users { get; set; }
    
        public virtual ObjectResult<ProcMaster_User_Result> ProcMaster_User(string action, Nullable<int> usrno, string mobile, string name, string email, string aspNetID, string userID, string password, string referralCode, Nullable<int> createdByUserID, Nullable<int> userTypeId)
        {
            var actionParameter = action != null ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(string));
    
            var usrnoParameter = usrno.HasValue ?
                new ObjectParameter("Usrno", usrno) :
                new ObjectParameter("Usrno", typeof(int));
    
            var mobileParameter = mobile != null ?
                new ObjectParameter("Mobile", mobile) :
                new ObjectParameter("Mobile", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var aspNetIDParameter = aspNetID != null ?
                new ObjectParameter("AspNetID", aspNetID) :
                new ObjectParameter("AspNetID", typeof(string));
    
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var referralCodeParameter = referralCode != null ?
                new ObjectParameter("ReferralCode", referralCode) :
                new ObjectParameter("ReferralCode", typeof(string));
    
            var createdByUserIDParameter = createdByUserID.HasValue ?
                new ObjectParameter("CreatedByUserID", createdByUserID) :
                new ObjectParameter("CreatedByUserID", typeof(int));
    
            var userTypeIdParameter = userTypeId.HasValue ?
                new ObjectParameter("UserTypeId", userTypeId) :
                new ObjectParameter("UserTypeId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcMaster_User_Result>("ProcMaster_User", actionParameter, usrnoParameter, mobileParameter, nameParameter, emailParameter, aspNetIDParameter, userIDParameter, passwordParameter, referralCodeParameter, createdByUserIDParameter, userTypeIdParameter);
        }
    
        public virtual ObjectResult<ProcMaster_MainWallet_Result> ProcMaster_MainWallet(Nullable<int> usrNo, Nullable<decimal> amount, string factor, string narration, Nullable<int> isReturn, string remark, string transactionId)
        {
            var usrNoParameter = usrNo.HasValue ?
                new ObjectParameter("UsrNo", usrNo) :
                new ObjectParameter("UsrNo", typeof(int));
    
            var amountParameter = amount.HasValue ?
                new ObjectParameter("Amount", amount) :
                new ObjectParameter("Amount", typeof(decimal));
    
            var factorParameter = factor != null ?
                new ObjectParameter("Factor", factor) :
                new ObjectParameter("Factor", typeof(string));
    
            var narrationParameter = narration != null ?
                new ObjectParameter("Narration", narration) :
                new ObjectParameter("Narration", typeof(string));
    
            var isReturnParameter = isReturn.HasValue ?
                new ObjectParameter("IsReturn", isReturn) :
                new ObjectParameter("IsReturn", typeof(int));
    
            var remarkParameter = remark != null ?
                new ObjectParameter("Remark", remark) :
                new ObjectParameter("Remark", typeof(string));
    
            var transactionIdParameter = transactionId != null ?
                new ObjectParameter("TransactionId", transactionId) :
                new ObjectParameter("TransactionId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProcMaster_MainWallet_Result>("ProcMaster_MainWallet", usrNoParameter, amountParameter, factorParameter, narrationParameter, isReturnParameter, remarkParameter, transactionIdParameter);
        }
    }
}
