//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelPortal.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Users
    {
        public string RoleId { get; set; }
        public string UserType { get; set; }
        public int ID { get; set; }
        public Nullable<int> Usrno { get; set; }
        public string AspNetID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string UserID { get; set; }
        public string Password { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Pincode { get; set; }
        public string Country { get; set; }
        public Nullable<int> PackageID { get; set; }
        public Nullable<int> IntroUsrno { get; set; }
        public string IntroStr { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> DOA { get; set; }
        public bool IsDelete { get; set; }
        public bool IsBlock { get; set; }
        public System.DateTime AddDate { get; set; }
        public string Photo { get; set; }
        public int CreatedByUserID { get; set; }
        public Nullable<bool> IsSales { get; set; }
        public Nullable<bool> IsPaymentByCC { get; set; }
        public Nullable<bool> IsPaymentByAccount { get; set; }
        public Nullable<bool> IsUseLogo { get; set; }
        public Nullable<bool> IsKycCompleted { get; set; }
        public Nullable<int> UserTypeID { get; set; }
        public string RegisterOTP { get; set; }
        public Nullable<bool> IsContract { get; set; }
        public Nullable<bool> IsToken { get; set; }
        public string LookLimitPeriodType { get; set; }
        public Nullable<int> FlightLookLimit { get; set; }
        public Nullable<bool> IsSupplier { get; set; }
        public string SupplierAgreement { get; set; }
        public string AgreementRemark { get; set; }
        public string Status { get; set; }
    }
}
